/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.HeadlessException;

/**
 *
 * @author Usuario
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaResultado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnRectangulo = new javax.swing.JButton();
        btnCuadrado = new javax.swing.JButton();
        btnTriangulo = new javax.swing.JButton();
        btnTrapecio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GeoCalc Studio");

        txaResultado.setBackground(new java.awt.Color(214, 255, 203));
        txaResultado.setColumns(20);
        txaResultado.setRows(5);
        txaResultado.setText("\n");
        jScrollPane1.setViewportView(txaResultado);

        jLabel1.setBackground(new java.awt.Color(75, 0, 182));
        jLabel1.setText("   Menú Principal");

        btnRectangulo.setBackground(new java.awt.Color(255, 136, 39));
        btnRectangulo.setText("Rectángulo");
        btnRectangulo.addActionListener(this::btnRectanguloActionPerformed);

        btnCuadrado.setBackground(new java.awt.Color(139, 189, 250));
        btnCuadrado.setText("Cuadrado");
        btnCuadrado.addActionListener(this::btnCuadradoActionPerformed);

        btnTriangulo.setBackground(new java.awt.Color(255, 236, 100));
        btnTriangulo.setText("Triángulo");
        btnTriangulo.addActionListener(this::btnTrianguloActionPerformed);

        btnTrapecio.setBackground(new java.awt.Color(164, 238, 84));
        btnTrapecio.setText("Trapecio");
        btnTrapecio.addActionListener(this::btnTrapecioActionPerformed);

        jLabel2.setText("   GeoCalc Studio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRectangulo)
                            .addComponent(btnCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectanguloActionPerformed
        try {
    String inputBase = javax.swing.JOptionPane.showInputDialog(this, "Ingrese la base del rectángulo:");
    String inputAltura = javax.swing.JOptionPane.showInputDialog(this, "Ingrese la altura del rectángulo:");
    
    if (inputBase != null && inputAltura != null) {
        double base = Double.parseDouble(inputBase);
        double altura = Double.parseDouble(inputAltura);
        
        modelo.Rectangulo r = new modelo.Rectangulo(base, altura);
        txaResultado.setText("--- RECTÁNGULO ---\nÁrea: " + r.area() + "\nPerímetro: " + r.perimetro());
    }
} catch (Exception e) {
    txaResultado.setText("Error: Ingrese valores numéricos válidos.");
}
    }//GEN-LAST:event_btnRectanguloActionPerformed

    private void btnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuadradoActionPerformed
       try {
    String inputLado = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el lado del cuadrado:");
    if (inputLado != null && !inputLado.trim().isEmpty()) {
        double lado = Double.parseDouble(inputLado);
        
        
        modelo.Cuadrado c = new modelo.Cuadrado(lado);
        txaResultado.setText("--- CUADRADO ---\nÁrea: " + c.area() + "\nPerímetro: " + c.perimetro());
        } else {
                txaResultado.setText("Operación cancelada o campo vacío.");
                }
        } catch (NumberFormatException e) {
          txaResultado.setText("Error: Ingrese un número válido.");
       } catch (HeadlessException e) {
    txaResultado.setText("Error en el cálculo: " + e.getMessage());
}
    }//GEN-LAST:event_btnCuadradoActionPerformed

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        try {
    String inputBase = javax.swing.JOptionPane.showInputDialog(this, "Ingrese la base del triángulo:");
    String inputAltura = javax.swing.JOptionPane.showInputDialog(this, "Ingrese la altura del triángulo:");
    
    if (inputBase != null && inputAltura != null) {
        double base = Double.parseDouble(inputBase);
        double altura = Double.parseDouble(inputAltura);
        
        modelo.Triangulo t = new modelo.Triangulo(base, altura, base, base, base);
        txaResultado.setText("--- TRIÁNGULO ---\nÁrea: " + t.area() + "\nPerímetro: " + t.perimetro());
    }
} catch (Exception e) {
    txaResultado.setText("Error: Ingrese valores numéricos válidos.");
}
    }//GEN-LAST:event_btnTrianguloActionPerformed

    private void btnTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrapecioActionPerformed
        try {
    String inputBMayor = javax.swing.JOptionPane.showInputDialog(this, "Ingrese la base mayor:");
    String inputBMenor = javax.swing.JOptionPane.showInputDialog(this, "Ingrese la base menor:");
    
    if (inputBMayor != null && inputBMenor != null) {
        double bMayor = Double.parseDouble(inputBMayor);
        double bMenor = Double.parseDouble(inputBMenor);
        
        modelo.Trapecio tp = new modelo.Trapecio(bMayor, bMenor, bMayor, bMayor, bMayor);
        txaResultado.setText("--- TRAPECIO ---\nÁrea: " + tp.area() + "\nPerímetro: " + tp.perimetro());
    }
} catch (Exception e) {
    txaResultado.setText("Error: Ingrese valores numéricos válidos.");
}
    }//GEN-LAST:event_btnTrapecioActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuadrado;
    private javax.swing.JButton btnRectangulo;
    private javax.swing.JButton btnTrapecio;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaResultado;
    // End of variables declaration//GEN-END:variables
}
